# Generated by Django 4.1.7 on 2023-03-03 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed072b31-4a73-43fb-857c-2f2ec6add414'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
