# Generated by Django 4.1.7 on 2023-03-03 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_see_all_loans', 'See all the loaned books'))},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d1ba44b-1144-49e5-a656-b90ffab926a2'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
